### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by yonkov**
Hi Bartek, here is my work so far. 

**Disclaimer:** I have never used python and django before.
### What I did
1. I was able to run the api on Windows and show the data with react. What i did so far:
2. I went really quick through the documentation to get an idea how to do things with django.
3. I expanded the Trip model to include fields with services
4. I added admin functionality and add put data through the admin dashboard
5. I created user group that allows to add/update/delete trips with services and nothing more
6. I added image thumbnails and some styles and small effects to improve the UX of the app
7. I added routing with reac-router-dom and implemeted trip-details view that is acessible via query params
8. I tried to add extra models for each service in the backend, however I was only able to send emty objects to the database

### What still needs to be done

1. There is currently only one model in the database, which leads to a couple of problems:
- all users from the "service givers" user group can update not only the service they are providing, but also the trips
- all admins can post services but they can also delete and edit each other services
- there is no reliable way to estimate total cost

That is why, I tried to update the database to add each service as a different model, with one to many ref to the Trip model. In this way, it can the user will be able to add/update only his own service. However, I would need to spend more time with the documentation or maybe a bit help from your side to find out how to do it. 

Please let me know if there is a way to improve the existing code or maybe I should use a completely different approach.

### CODE REVIEW

**Comment by bartek** [comment]
Hi @yonkov !

Thanks for your time doing this. Upon reviewing your PR, I am seeing much of the functionality requested in the challenge is not complete, but is _partially_ complete (commented out)

Do you mind taking the time to complete it as per the README? We'd be happy to give you more time (no rush right now!) and allow you to do it right, as seems like you were heading there anyways :)

**Comment by yonkov** [comment]
Hi Bartek,

Thank you for giving me extra time. After going through the Django's documentation, I was finally able to construct the models. I created one-to-many relationship between a service (hotel, transportation and accomodation) and a trip and I was able to do a reverted object reference to get a list of services for a given trip. Final result:

**1. The app lists trips in react.js**
**2. Users are able to add services (Hotels, Accommodations and Transportation) to a given trip.**

- Every user from the Service Givers user group can view and add a service (hotel, accomodation or transportation) to a corresponding trip through the django admin interface. They are no longer able to edit/delete a whole trip and they are not able to delete each other's services. 

**3. Each service has a name, a location, a type and a cost** 
- All these properties are accessible on the frontend. Each service is a different model on the Django backend

**4. The frontend calls the backend via an API call**

**5. The website layout is fully responsive**
**6. Routing is implemented on the frontend for better user experience.** 
- Different views for list all trips and details

**Comment by bartek** [comment]
@yonkov Thanks for this!

Unfortunately, I am running it and I get an error (see below)

I've run the Django server and ran `webpack` to build the bundle. Are we by chance running different versions of react-router (or another package)?

**Comment by yonkov** [comment]
Hi Bart, I tested the app by downloading the dev branch from m github repo and reinstalling all dependencies with 

> npm install

. It is working on my side (I do get these warnings in the console but the app is working!) You have a blank screen when you run the app on http://localhost:8000/
image

**Comment by bartek** [comment]
@yonkov Seems like `trip` is core to that component, so my assumption was it being `undefined` was bad news. I misread your comments prior and assumed you had built service-add functionality on the front end, but I see it's on the backend.

Ok, thank you! The weekend is coming up, so we'll be discussing next steps amongst the team early next week

**Comment by bartek** [comment]
@yonkov Are you able to add functionality to this application so that I can add a service via the React front-end, rather than just the Django admin?

Thanks

**Comment by yonkov** [comment]
Hi Bartek!
It is of course possible to add a form in the frontend (on the details page) that sends data to the backend, however, this week I have a lot of work, so I am not sure that I will have time. Currently, you can indeed post data with Django admin (if the user belongs to a specific group, he can add a service from there but no other admin functionalities) . Were you able to run the project?

**Comment by bartek** [comment]
@yonkov I am, yup. No problem if you can't get to it this week. I would like to see that front-end component as it's definitely an ask of the challenge.

**Comment by yonkov** [comment]
@bartek, I have just added a form for hotels, tomorrow I will also add forms for the other two services (accomodation and transportation). It works for non-registered users only (since frontend authentication is still not implemented).
image

**Comment by yonkov** [comment]
Hi @bartek ,
I added the services to the frontend (details page) and improved the user interface. I used css modules and reconfigured webpack (you will need to install the required dependecies with npm install). I added some nice icons with font awesome and implemented some additional functionalities such as the option to toggle the forms with the services. Let me know what you think.

image
image

**Pull request closed without merging**
